# Generated by Django 5.1.2 on 2025-05-29 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_is_favourite_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='books.book'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='books.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'book')},
        ),
    ]
