# Generated by Django 5.1.2 on 2025-06-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_is_read_userbookstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookstatus',
            name='is_read',
        ),
        migrations.AddField(
            model_name='userbookstatus',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('reading', 'Reading'), ('finished', 'Finished Reading')], default='not_started', max_length=20),
        ),
    ]
